import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { AgentMatrix } from "@/components/agent-matrix";
import { ApprovalModal } from "@/components/approval-modal";
import { StatusBadge } from "@/components/status-badge";
import { DecisionMatrix } from "@/components/features/decision-matrix";
import { DecisionTheatre } from "@/components/features/decision-theatre";
const execution = {execution_id:"12345678-abcd",correlation_id:"cid",status:"WAITING_APPROVAL" as const,risk_level:"HIGH",data_sensitivity:"INTERNAL",current_node:"approval",created_at:"",updated_at:"",evidence:["Blast radius exceeds threshold"]};
describe("Mission Control components",()=>{
  it("renders all agent matrix telemetry",()=>{ render(<AgentMatrix agents={[{id:"risk_analysis",role:"Change risk",status:"COMPLETED",modelClass:"REASONING",provider:"litellm",model:"reasoning",placement:"eu-api",routeReason:"criticality",fallbackAllowed:true,policyOutcome:"ALLOWED",latency:420,promptTokens:125,completionTokens:68,cost:.00042,outcome:"Success"}]}/>); expect(screen.getByText("risk analysis")).toBeInTheDocument(); expect(screen.getByText("420 ms")).toBeInTheDocument(); expect(screen.getByText("Success")).toBeInTheDocument(); });
  it("uses accessible human-readable statuses",()=>{render(<StatusBadge status="WAITING_APPROVAL"/>);expect(screen.getByText("Waiting Approval")).toBeInTheDocument()});
  it("captures rationale and approves",async()=>{const user=userEvent.setup();const action=vi.fn().mockResolvedValue(undefined);render(<ApprovalModal execution={execution} busy={false} onDecision={action}/>);expect(screen.getByRole("dialog",{name:"Human decision required"})).toBeInTheDocument();expect(screen.getByText("Blast radius exceeds threshold")).toBeInTheDocument();await user.type(screen.getByRole("textbox"),"Rollback verified");await user.click(screen.getByRole("button",{name:"Approve & resume"}));expect(action).toHaveBeenCalledWith("approve","Rollback verified")});
  it("supports explicit rejection",async()=>{const user=userEvent.setup();const action=vi.fn().mockResolvedValue(undefined);render(<ApprovalModal execution={execution} busy={false} onDecision={action}/>);await user.click(screen.getByRole("button",{name:"Reject change"}));expect(action).toHaveBeenCalledWith("reject","")});
  it("dismisses the approval dialog with Escape",async()=>{const user=userEvent.setup();const dismiss=vi.fn();render(<ApprovalModal execution={execution} busy={false} onDecision={vi.fn()} onDismiss={dismiss}/>);await user.keyboard("{Escape}");expect(dismiss).toHaveBeenCalledOnce()});
  it("filters matrix tasks and supports arrow-key navigation",async()=>{const user=userEvent.setup();render(<DecisionMatrix agents={[]} onSelect={vi.fn()}/>);const intake=screen.getAllByRole("button",{name:/Change request intake/})[0];intake.focus();await user.keyboard("{ArrowRight}");expect(document.activeElement).not.toBe(intake);await user.type(screen.getByPlaceholderText("Search agents…"),"residency");expect(screen.getAllByRole("button",{name:/Residency classifier/})).not.toHaveLength(0);expect(screen.queryByRole("button",{name:/Change request intake/})).not.toBeInTheDocument()});
  it("renders persisted agent-to-agent briefings in the decision theatre",()=>{render(<DecisionTheatre events={[{schema_version:"1.0",event_id:"m1",sequence:4,execution_id:"e1",correlation_id:"c1",timestamp:"2026-08-23T12:00:00Z",event_type:"agent.message",agent_id:"challenge-agent",status:"COMPLETED",model_class:null,provider:null,message_kind:"handoff",message:"Material trade-off identified.",recipient:"policy-evaluator",evidence_refs:["challenge:material-trade-off"],latency_ms:null,prompt_tokens:null,completion_tokens:null,estimated_cost_eur:null,trace_id:"t1"}]}/>);expect(screen.getByText("Material trade-off identified.")).toBeInTheDocument();expect(screen.getByText("challenge:material-trade-off")).toBeInTheDocument();expect(screen.getByRole("list",{name:"Persisted agent handoffs"})).toBeInTheDocument()});
});
