"use client";
import { useCallback, useMemo, useReducer, useState } from "react";
import { createExecution, decide } from "@/lib/api";
import { initialDashboardState, telemetryReducer } from "@/lib/telemetry";
import { useExecutionStream } from "@/hooks/use-execution-stream";
import { AgentMatrix } from "./agent-matrix";
import { ApprovalModal } from "./approval-modal";
import { StatusBadge } from "./status-badge";

export function MissionControl() {
  const [state, dispatch] = useReducer(telemetryReducer, initialDashboardState);
  const [request, setRequest] = useState("Assess whether the proposed production infrastructure change should proceed.");
  const [scenario, setScenario] = useState("HIGH_RISK"); const [busy, setBusy] = useState(false);
  const connection = useCallback((value: typeof state.connection) => dispatch({ type: "connection", value }), []);
  useExecutionStream(state.execution?.execution_id ?? null, dispatch, connection);
  async function start() { setBusy(true); try { const execution = await createExecution({ request, scenario }); dispatch({ type: "execution", execution }); } catch (error) { dispatch({ type: "error", error: error instanceof Error ? error.message : "Unable to start execution" }); } finally { setBusy(false); } }
  async function decision(choice: "approve" | "reject", reason: string) { if (!state.execution) return; setBusy(true); try { const execution = await decide(state.execution.execution_id, choice, reason || `${choice === "approve" ? "Risk accepted" : "Risk declined"} by Mission Control operator`); dispatch({ type: "execution", execution }); } catch (error) { dispatch({ type: "error", error: error instanceof Error ? error.message : "Decision failed" }); } finally { setBusy(false); } }
  const agents = Object.values(state.agents); const totals = useMemo(() => agents.reduce((a, x) => ({ tokens: a.tokens + x.promptTokens + x.completionTokens, cost: a.cost + x.cost, latency: a.latency + x.latency }), { tokens: 0, cost: 0, latency: 0 }), [agents]);
  return <main><header><div className="brandmark">N</div><div><div className="eyebrow">Neuromorphic Inference · Control plane</div><h1>Enterprise Sovereign AI <span>Mission Control</span></h1></div><div className="header-state"><span className={`connection ${state.connection}`} />{state.connection === "reconnecting" ? "Reconnecting telemetry" : state.connection === "connected" ? "Telemetry live" : "Control plane ready"}</div></header>
    <section className="command panel"><div><div className="eyebrow">New decision workflow</div><h2>Enterprise change risk assessment</h2></div><textarea aria-label="Decision request" value={request} onChange={e => setRequest(e.target.value)} /><select aria-label="Demo scenario" value={scenario} onChange={e => setScenario(e.target.value)}><option value="SAFE">Low-risk public</option><option value="HIGH_RISK">High-risk · HITL</option><option value="SENSITIVE">Sensitive · sovereign</option><option value="PROVIDER_FAILURE">Provider failure</option></select><button className="button primary" disabled={busy || !request.trim()} onClick={() => void start()}>{busy ? "Dispatching…" : "Launch assessment"}</button></section>
    {state.error && <div className="error-banner" role="alert"><strong>Control plane error</strong><span>{state.error}</span></div>}
    <section className="kpis"><Kpi label="Active execution" value={state.execution ? <StatusBadge status={state.execution.status}/> : "Standby"} detail={state.execution ? `Node · ${state.execution.current_node}` : "Awaiting mission"}/><Kpi label="Token volume" value={totals.tokens.toLocaleString()} detail="Prompt + completion"/><Kpi label="Estimated cost" value={`€${totals.cost.toFixed(5)}`} detail="Calculated server-side"/><Kpi label="Agent latency" value={`${totals.latency} ms`} detail={`${agents.filter(a=>a.outcome === "Success").length}/${agents.length || 0} successful`}/></section>
    <div className="workspace"><section className="panel matrix"><div className="panel-heading"><div><div className="eyebrow">Decision matrix</div><h2>Agent operations</h2></div><span className="live-pill">● LIVE</span></div><AgentMatrix agents={agents}/></section><aside className="panel timeline"><div className="eyebrow">Execution lineage</div><h2>Timeline</h2>{state.events.length ? <ol>{[...state.events].reverse().slice(0,8).map(e => <li key={e.event_id}><span className="timeline-dot"/><div><strong>{e.event_type.replaceAll(".", " · ")}</strong><small>{e.agent_id?.replaceAll("_", " ") ?? "orchestrator"} · {new Date(e.timestamp).toLocaleTimeString()}</small></div></li>)}</ol> : <div className="empty timeline-empty">Telemetry and audit milestones appear here.</div>}</aside></div>
    <section className="lower-grid"><div className="panel routing"><div className="eyebrow">Policy routing</div><h2>Sovereignty boundary</h2><div className="route-flow"><span>Task policy</span><b>→</b><span className={scenario === "SENSITIVE" ? "sovereign" : "cloud"}>{scenario === "SENSITIVE" ? "SOVEREIGN" : scenario === "HIGH_RISK" ? "REASONING" : "FAST"}</span><b>→</b><span>{scenario === "SENSITIVE" ? "Ollama · local" : "LiteLLM gateway"}</span></div><p className="muted">Restricted data fails closed: cloud fallback is prohibited by policy.</p></div><div className="panel trace"><div className="eyebrow">Observability</div><h2>Trace correlation</h2><code>{state.events.find(e=>e.trace_id)?.trace_id ?? state.execution?.correlation_id ?? "No active trace"}</code><p className="muted">Execution, routing, cost and agent spans share one correlation chain.</p></div></section>
    {state.execution?.status === "WAITING_APPROVAL" && <ApprovalModal execution={state.execution} busy={busy} onDecision={decision}/>}<footer>Enterprise Sovereign AI Decision Matrix <span>Deterministic orchestration · Human accountability · Local-first privacy</span></footer></main>;
}
function Kpi({ label, value, detail }: { label: string; value: React.ReactNode; detail: string }) { return <article className="panel kpi"><div className="eyebrow">{label}</div><div className="kpi-value">{value}</div><small>{detail}</small></article>; }
